name: build-and-test-workflow

on:
  push:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # pulls all commits (needed for lerna / semantic release to correctly version)
        fetch-depth: '0'
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Build packages
      run: yarn build
    - name: Run yarn lint
      run: yarn lint
      
    - name: Run unit tests
      run: yarn test
